# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/workplace/project_light_student_number/project_light_student_number.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/workplace/project_light_student_number/project_light_student_number.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Xilinx/workplace/project_light_student_number/project_light_student_number.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/Xilinx/workplace/project_light_student_number/project_light_student_number.srcs/sources_1/new/lightstudentnum.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Xilinx/workplace/project_light_student_number/project_light_student_number.srcs/constrs_2/new/light.xdc
set_property used_in_implementation false [get_files D:/Xilinx/workplace/project_light_student_number/project_light_student_number.srcs/constrs_2/new/light.xdc]


synth_design -top lightstudentnum -part xc7a35ticpg236-1L


write_checkpoint -force -noxdef lightstudentnum.dcp

catch { report_utilization -file lightstudentnum_utilization_synth.rpt -pb lightstudentnum_utilization_synth.pb }
