USE School

SELECT STUDENTS.sid,STUDENTS.sname
FROM STUDENTS,CHOICES,COURSES
WHERE CHOICES.cid=COURSES.cid and COURSES.cname='C++' and CHOICES.sid=STUDENTS.sid and CHOICES.score>(
	SELECT CHOICES.score
	FROM STUDENTS,CHOICES,COURSES
	WHERE CHOICES.cid=COURSES.cid and COURSES.cname='C++' and STUDENTS.sid=CHOICES.sid and STUDENTS.sname='ZNKOO'
)

SELECT SNAME 
FROM STUDENTS
WHERE grade IN
(
	SELECT grade
	FROM STUDENTS
	WHERE sid=883794999 or sid=850955252
)

SELECT sname
FROM STUDENTS
WHERE sname NOT IN
	(
		SELECT STUDENTS.sname
		FROM COURSES,STUDENTS,CHOICES
		WHERE COURSES.cname='Java'
		      AND COURSES.cid=CHOICES.cid
		      AND CHOICES.sid=STUDENTS.sid
	)
	
SELECT *
FROM COURSES
WHERE COURSES.hour<=ALL
	(
		SELECT HOUR
		FROM COURSES
		WHERE hour IS NOT NULL
	)
	
SELECT TEACHERS.tid,CHOICES.CID
FROM TEACHERS,CHOICES
WHERE  CHOICES.tid=TEACHERS.tid
	AND TEACHERS.salary>=ALL
	(
		SELECT salary
		FROM TEACHERS
		WHERE salary IS NOT NULL
	)
ORDER BY TEACHERS.tid

SELECT STUDENTS.sid
FROM STUDENTS,CHOICES,COURSES
WHERE  CHOICES.cid=COURSES.cid
	AND STUDENTS.sid=CHOICES.sid
	AND COURSES.cname='ERP'
	AND CHOICES.score>=ALL
	(
		SELECT CHOICES.score
		FROM CHOICES,COURSES
		WHERE CHOICES.cid=COURSES.cid
			  AND COURSES.cname='ERP'
			  AND CHOICES.score IS NOT NULL
	)
ORDER BY STUDENTS.sid

SELECT CNAME
FROM COURSES
WHERE cname NOT IN
(
	SELECT DISTINCT COURSES.cname
	FROM COURSES,CHOICES
	WHERE COURSES.cid = CHOICES.cid
)

SELECT DISTINCT COURSES.CNAME
FROM COURSES,CHOICES
WHERE COURSES.cid=CHOICES.cid
	AND CHOICES.tid in
	(
		SELECT DISTINCT CHOICES.tid
		FROM COURSES,CHOICES
		WHERE COURSES.cid = CHOICES.cid 
			  AND COURSES.CNAME='UML'
	)

SELECT SID
FROM CHOICES
WHERE CHOICES.cid=
(
	SELECT COURSES.cid
	FROM COURSES
	WHERE COURSES.cname='database'
)
INTERSECT
SELECT SID
FROM CHOICES
WHERE CHOICES.cid=
(
	SELECT COURSES.cid
	FROM COURSES
	WHERE COURSES.cname='UML'
)

SELECT SID
FROM CHOICES
WHERE CHOICES.cid=
(
	SELECT COURSES.cid
	FROM COURSES
	WHERE COURSES.cname='database'
)
EXCEPT
SELECT SID
FROM CHOICES
WHERE CHOICES.cid=
(
	SELECT COURSES.cid
	FROM COURSES
	WHERE COURSES.cname='UML'
)

