use master
if exists(select * from sysdatabases where name='lab2')
drop database lab2

create database lab2
use lab2

CREATE TABLE CUSTOMERS(
	CID INT NOT NULL UNIQUE,
	CNAME CHAR(20) NOT NULL,
	CITY CHAR(20) NOT NULL,
	DISCNT FLOAT,
	PRIMARY KEY(CID)
)

CREATE TABLE AGENTS(
	AID INT NOT NULL UNIQUE,
	ANAME CHAR(20) NOT NULL,
	CITY CHAR(20) NOT NULL,
	PERCENTS FLOAT,
	PRIMARY KEY(AID)
)

CREATE TABLE PRODUCTS(
	PID INT NOT NULL UNIQUE,
	PNAME CHAR(20) NOT NULL,
	PRIMARY KEY(PID)
)

CREATE TABLE ORDERS(
	ORDNA INT NOT NULL UNIQUE,
	MONTH INT NOT NULL,
	CID INT NOT NULL UNIQUE,
	AID INT NOT NULL UNIQUE,
	PID INT NOT NULL UNIQUE,
	PRIMARY KEY(ORDNA),
	FOREIGN KEY(CID) REFERENCES CUSTOMERS ON DELETE CASCADE,
	FOREIGN KEY(AID) REFERENCES AGENTS ON DELETE CASCADE,
	FOREIGN KEY(PID) REFERENCES PRODUCTS ON DELETE CASCADE
)

ALTER TABLE PRODUCTS ADD CITY CHAR(20)
ALTER TABLE PRODUCTS ADD QUANTITY FLOAT
ALTER TABLE PRODUCTS ADD PRICE FLOAT

CREATE INDEX ID on CUSTOMERS(CID)
CREATE INDEX ID on AGENTS(AID)
CREATE INDEX ID on PRODUCTS(PID)
CREATE INDEX ID on ORDERS(ORDNA)

DROP INDEX CUSTOMERS.ID
DROP INDEX AGENTS.ID
DROP INDEX PRODUCTS.ID
DROP INDEX ORDERS.ID