USE School

SELECT * FROM COURSES

SELECT DISTINCT SID FROM CHOICES

SELECT CID FROM COURSES 
WHERE hour < 88

SELECT SID FROM CHOICES
GROUP BY SID
HAVING SUM(SCORE) > 400

SELECT COUNT(CNAME) as '课程总数' FROM COURSES

SELECT CHOICES.CID,COURSES.CNAME,COUNT(CHOICES.sid) as '选课人数'
FROM CHOICES,COURSES
WHERE CHOICES.CID=COURSES.CID
GROUP BY CHOICES.CID,COURSES.CNAME

SELECT SID 
FROM CHOICES
WHERE score>60
GROUP BY SID
HAVING COUNT(*)>2

SELECT SID,COUNT(NO) as '选修课程数', AVG(SCORE) as '平均成绩'
FROM CHOICES	
GROUP BY SID
ORDER BY SID

select CHOICES.sid,STUDENTS.sname
FROM CHOICES,STUDENTS,COURSES
WHERE CHOICES.cid=COURSES.cid AND COURSES.cname='Java' AND CHOICES.sid=STUDENTS.sid

select CHOICES.cid,CHOICES.score
FROM CHOICES,STUDENTS
WHERE CHOICES.sid=STUDENTS.SID AND STUDENTS.sname='sssht'

select X.CNAME
FROM COURSES AS X,COURSES AS Y
WHERE Y.cname='C++'	AND X.hour > Y.hour
